# Generated by Django 4.1.5 on 2023-02-09 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(
                choices=[('Open', 'Open'), ('Closed', 'Closed')],
                default='Open',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message='First Name must consist of 3-50 letters',
                        regex='^[A-Za-z\\s]{3,}$',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Last Name must consist of 3-50 letters',
                        regex='^[A-Za-z\\s]{3,}$',
                    )
                ],
            ),
        ),
    ]
