# Generated by Django 4.1.5 on 2023-02-01 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_alter_specialistdepartment_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistmessage',
            name='responder',
            field=models.ForeignKey(db_column='responder', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
