# Generated by Django 4.1.5 on 2023-01-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_department_message_studentmessage_ticket_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='specialistdepartment',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='specialistdepartment',
            old_name='specialist_id',
            new_name='specialist',
        ),
        migrations.RenameField(
            model_name='specialistinbox',
            old_name='specialist_id',
            new_name='specialist',
        ),
        migrations.RenameField(
            model_name='specialistinbox',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='specialistmessage',
            old_name='responder_id',
            new_name='responder',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='student_id',
            new_name='student',
        ),
    ]
