# Generated by Django 4.1.6 on 2023-02-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.SlugField(default='open', max_length=20),
        ),
    ]
