# Generated by Django 4.1.5 on 2023-02-13 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticketing.models.validators.user_validator


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_ticket_status_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistdepartment',
            name='specialist',
            field=models.ForeignKey(
                db_column='specialist',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                validators=[
                    ticketing.models.validators.user_validator.validate_user_as_specialist
                ],
            ),
        ),
        migrations.AlterField(
            model_name='specialistinbox',
            name='specialist',
            field=models.ForeignKey(
                db_column='specialist',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                validators=[
                    ticketing.models.validators.user_validator.validate_user_as_specialist
                ],
            ),
        ),
        migrations.AlterField(
            model_name='specialistmessage',
            name='responder',
            field=models.ForeignKey(
                db_column='responder',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                validators=[
                    ticketing.models.validators.user_validator.validate_user_as_specialist
                ],
            ),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='student',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                validators=[
                    ticketing.models.validators.user_validator.validate_user_as_student
                ],
            ),
        ),
    ]
