from . import auth
from . import home
from . import specialist_inbox
from . import student_inbox
from . import specialist_claim_ticket
from . import student_ticket
from . import student_message
from . import ticket_view
from . import edit_department
from . import change_password
from . import edit_user
from . import director_panel
from . import department_manager
from . import auth
from . import home
from . import specialist_inbox
from . import student_inbox
from . import specialist_claim_ticket
from . import student_ticket
from . import department_faq
from . import base_faq
from . import specialist_faq_form
from . import individual_specialist_faq
from . import update_faq
from . import delete_faq
from . import specialist_department_faq
from . import search_bar
